//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetChanger.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0" )]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class fa_IR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
        internal fa_IR()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ( object.ReferenceEquals( resourceMan, null ) ) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager( "NetChanger.Resources.fa-IR", typeof( fa_IR ).Assembly );
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to درباره.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString( "about", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString( "address", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to متاسفانه ظاهرا مجوز مدیر به برنامه داده نشده، نمی‌توانیم به کار ادامه دهیم..
        /// </summary>
        public static string admin_rights_needed {
            get {
                return ResourceManager.GetString( "admin_rights_needed", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString( "cancel", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString( "close", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ایجاد یک نمایه جدید....
        /// </summary>
        public static string create_new_profile {
            get {
                return ResourceManager.GetString( "create_new_profile", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString( "delete", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف این مورد مطمئن هستید؟ این کار غیر قابل بازگشت است..
        /// </summary>
        public static string delete_confirmation {
            get {
                return ResourceManager.GetString( "delete_confirmation", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تایید حذف!!.
        /// </summary>
        public static string delete_confirmation_title {
            get {
                return ResourceManager.GetString( "delete_confirmation_title", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DHCP.
        /// </summary>
        public static string dhcp {
            get {
                return ResourceManager.GetString( "dhcp", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to پایین.
        /// </summary>
        public static string down {
            get {
                return ResourceManager.GetString( "down", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کپی.
        /// </summary>
        public static string duplicate {
            get {
                return ResourceManager.GetString( "duplicate", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString( "edit", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ویرایش نمایه جاری....
        /// </summary>
        public static string edit_current_profile {
            get {
                return ResourceManager.GetString( "edit_current_profile", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString( "en", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString( "error", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string fa {
            get {
                return ResourceManager.GetString( "fa", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to دروازه شبکه.
        /// </summary>
        public static string gateway {
            get {
                return ResourceManager.GetString( "gateway", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نام رابط شبکه.
        /// </summary>
        public static string interface_name {
            get {
                return ResourceManager.GetString( "interface_name", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تنظیمات آی پی.
        /// </summary>
        public static string ip_settings {
            get {
                return ResourceManager.GetString( "ip_settings", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString( "language", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لاگ نتایج دستورات.
        /// </summary>
        public static string log_of_command_results {
            get {
                return ResourceManager.GetString( "log_of_command_results", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مدیریت نمایه‌ها....
        /// </summary>
        public static string manage_profiles {
            get {
                return ResourceManager.GetString( "manage_profiles", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to سرورهای نام.
        /// </summary>
        public static string nameservers {
            get {
                return ResourceManager.GetString( "nameservers", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NetChanger.
        /// </summary>
        public static string netchagner {
            get {
                return ResourceManager.GetString( "netchagner", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ماسک شبکه.
        /// </summary>
        public static string netmask {
            get {
                return ResourceManager.GetString( "netmask", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string new_ {
            get {
                return ResourceManager.GetString( "new_", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رابط شبکه نمی‌تواند بدون نام باشد..
        /// </summary>
        public static string no_blank_interface_name {
            get {
                return ResourceManager.GetString( "no_blank_interface_name", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نام نمی‌تواند خالی باشد..
        /// </summary>
        public static string no_blank_name {
            get {
                return ResourceManager.GetString( "no_blank_name", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString( "ok", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نام نمایه.
        /// </summary>
        public static string profile_name {
            get {
                return ResourceManager.GetString( "profile_name", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نمایه‌ها.
        /// </summary>
        public static string profiles {
            get {
                return ResourceManager.GetString( "profiles", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to فهرست نمایه‌ها.
        /// </summary>
        public static string profiles_list {
            get {
                return ResourceManager.GetString( "profiles_list", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اجرا در هنگام راه اندازی سیستم.
        /// </summary>
        public static string put_in_startup {
            get {
                return ResourceManager.GetString( "put_in_startup", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string quit {
            get {
                return ResourceManager.GetString( "quit", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتشار این نسخه.
        /// </summary>
        public static string release_date_of_this_version {
            get {
                return ResourceManager.GetString( "release_date_of_this_version", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نمایش لاگ.
        /// </summary>
        public static string show_log {
            get {
                return ResourceManager.GetString( "show_log", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تنظیمات آی پی شبکه خود را به آسانی تغییر دهید!.
        /// </summary>
        public static string slogan {
            get {
                return ResourceManager.GetString( "slogan", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ایستا.
        /// </summary>
        public static string static_ {
            get {
                return ResourceManager.GetString( "static_", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بالا.
        /// </summary>
        public static string up {
            get {
                return ResourceManager.GetString( "up", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to دروازه شبکه آی پی درستی ندارد..
        /// </summary>
        public static string wrong_gateway {
            get {
                return ResourceManager.GetString( "wrong_gateway", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to آدرس آی پی درستی ندارد..
        /// </summary>
        public static string wrong_ip {
            get {
                return ResourceManager.GetString( "wrong_ip", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ماسک شبکه آی پی درستی ندارد..
        /// </summary>
        public static string wrong_netmask {
            get {
                return ResourceManager.GetString( "wrong_netmask", resourceCulture );
            }
        }
    }
}
