//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetChanger.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetChanger.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string addresses {
            get {
                return ResourceManager.GetString("addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I don&apos;t seem to be able to start this program with administrator rights!.
        /// </summary>
        public static string admin_rights_needed {
            get {
                return ResourceManager.GetString("admin_rights_needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cance&amp;l.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change proxy override.
        /// </summary>
        public static string change_proxy_override {
            get {
                return ResourceManager.GetString("change_proxy_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change proxy server.
        /// </summary>
        public static string change_proxy_server {
            get {
                return ResourceManager.GetString("change_proxy_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Profile....
        /// </summary>
        public static string create_new_profile {
            get {
                return ResourceManager.GetString("create_new_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string default1 {
            get {
                return ResourceManager.GetString("default1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this item? It cannot be undone..
        /// </summary>
        public static string delete_confirmation {
            get {
                return ResourceManager.GetString("delete_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete!!.
        /// </summary>
        public static string delete_confirmation_title {
            get {
                return ResourceManager.GetString("delete_confirmation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHCP.
        /// </summary>
        public static string dhcp {
            get {
                return ResourceManager.GetString("dhcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;uplicate.
        /// </summary>
        public static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit current profile....
        /// </summary>
        public static string edit_current_profile {
            get {
                return ResourceManager.GetString("edit_current_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Profiles.
        /// </summary>
        public static string export_profiles {
            get {
                return ResourceManager.GetString("export_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Gateway.
        /// </summary>
        public static string gateway {
            get {
                return ResourceManager.GetString("gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Profiles.
        /// </summary>
        public static string import_profiles {
            get {
                return ResourceManager.GetString("import_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Interface Name.
        /// </summary>
        public static string interface_name {
            get {
                return ResourceManager.GetString("interface_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Settings.
        /// </summary>
        public static string ip_settings {
            get {
                return ResourceManager.GetString("ip_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log of command results.
        /// </summary>
        public static string log_of_command_results {
            get {
                return ResourceManager.GetString("log_of_command_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Profiles....
        /// </summary>
        public static string manage_profiles {
            get {
                return ResourceManager.GetString("manage_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name&amp;servers.
        /// </summary>
        public static string nameservers {
            get {
                return ResourceManager.GetString("nameservers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetChanger.
        /// </summary>
        public static string netchagner {
            get {
                return ResourceManager.GetString("netchagner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Net Mask.
        /// </summary>
        public static string netmask {
            get {
                return ResourceManager.GetString("netmask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne&amp;w.
        /// </summary>
        public static string new_ {
            get {
                return ResourceManager.GetString("new_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface name cannot be blank..
        /// </summary>
        public static string no_blank_interface_name {
            get {
                return ResourceManager.GetString("no_blank_interface_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be blank..
        /// </summary>
        public static string no_blank_name {
            get {
                return ResourceManager.GetString("no_blank_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile&apos;s Name.
        /// </summary>
        public static string profile_name {
            get {
                return ResourceManager.GetString("profile_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string profiles {
            get {
                return ResourceManager.GetString("profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles List.
        /// </summary>
        public static string profiles_list {
            get {
                return ResourceManager.GetString("profiles_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string proxy {
            get {
                return ResourceManager.GetString("proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy IP address.
        /// </summary>
        public static string proxy_ip_address {
            get {
                return ResourceManager.GetString("proxy_ip_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Override.
        /// </summary>
        public static string proxy_override {
            get {
                return ResourceManager.GetString("proxy_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the addresses that you don&apos;t want to go through proxy. Use semicolons (;) to separate entries..
        /// </summary>
        public static string proxy_override_addresses_comment {
            get {
                return ResourceManager.GetString("proxy_override_addresses_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Port.
        /// </summary>
        public static string proxy_port {
            get {
                return ResourceManager.GetString("proxy_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Server.
        /// </summary>
        public static string proxy_server {
            get {
                return ResourceManager.GetString("proxy_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put in Startup.
        /// </summary>
        public static string put_in_startup {
            get {
                return ResourceManager.GetString("put_in_startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date of this version.
        /// </summary>
        public static string release_date_of_this_version {
            get {
                return ResourceManager.GetString("release_date_of_this_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log....
        /// </summary>
        public static string show_log {
            get {
                return ResourceManager.GetString("show_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your network IP settings easily!.
        /// </summary>
        public static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string static_ {
            get {
                return ResourceManager.GetString("static_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway isn&apos;t a correct IP..
        /// </summary>
        public static string wrong_gateway {
            get {
                return ResourceManager.GetString("wrong_gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address isn&apos;t a correct IP..
        /// </summary>
        public static string wrong_ip {
            get {
                return ResourceManager.GetString("wrong_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetMask isn&apos;t a correct IP..
        /// </summary>
        public static string wrong_netmask {
            get {
                return ResourceManager.GetString("wrong_netmask", resourceCulture);
            }
        }
    }
}
